apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - postgres.yaml
  - backend.yaml
  - back-end-app-service.yaml
  - fronttend.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml
